#!/usr/bin/env bash

# Usage:
#   $ git config core.hooksPath hooks/

function step() {
  color=$1
  message=$2
  printf "${color}>\n> ${message}\n>\n${S}"
}

G="\033[32m" # GREEN
R="\033[31m" # RED
Y="\033[33m" # YELLOW
S="\033[0m"  # RESET
TITLE="GIT HOOK PRE-COMMIT"

step ${Y} "${TITLE}"
make git_hooks_pre_commit

if [ $? -eq 0 ]; then
  step ${G} "${TITLE}: Everything is OK"
  exit 0
fi

step ${R} "${TITLE}: Something is wrong"
exit 1
