include file_1.inc
include file_2.inc
include file_3.inc

.DEFAULT_GOAL = vars
.PHONY: vars
vars: ## Show some Makefile variables
	@printf "$(Y)Vars:$(S)\n"
	@printf "\n$(Y)----$(S)\n"
	@printf "VAR_A: $(VAR_A)\n"
	@printf "VAR_B: $(VAR_B)\n"
	@printf "VAR_C: $(VAR_C)\n"